// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj636ZIdqndahbmEZ1XwDcrRaG07LKvAU',
    appId: '1:726868644910:android:2700a63ddd08fdd4c33bbf',
    messagingSenderId: '726868644910',
    projectId: 'abp-library-firebase-app',
    storageBucket: 'abp-library-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWR3mTUq6_rQRg9a3DcYPOl5j8LY-d6I',
    appId: '1:726868644910:ios:36fea65b1bb8a61bc33bbf',
    messagingSenderId: '726868644910',
    projectId: 'abp-library-firebase-app',
    storageBucket: 'abp-library-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.libraryAppAbp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNt5wEn4HIYoElrWpfzE47tOPKwllbJHI',
    appId: '1:726868644910:web:f377d55df7ad9115c33bbf',
    messagingSenderId: '726868644910',
    projectId: 'abp-library-firebase-app',
    authDomain: 'abp-library-firebase-app.firebaseapp.com',
    storageBucket: 'abp-library-firebase-app.firebasestorage.app',
    measurementId: 'G-5HRKFF7JEX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWR3mTUq6_rQRg9a3DcYPOl5j8LY-d6I',
    appId: '1:726868644910:ios:36fea65b1bb8a61bc33bbf',
    messagingSenderId: '726868644910',
    projectId: 'abp-library-firebase-app',
    storageBucket: 'abp-library-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.libraryAppAbp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNt5wEn4HIYoElrWpfzE47tOPKwllbJHI',
    appId: '1:726868644910:web:9e2e2fb1a6e034dfc33bbf',
    messagingSenderId: '726868644910',
    projectId: 'abp-library-firebase-app',
    authDomain: 'abp-library-firebase-app.firebaseapp.com',
    storageBucket: 'abp-library-firebase-app.firebasestorage.app',
    measurementId: 'G-FE6PN0VT3F',
  );

}